version: '1'

services:
  nginx:
    image: docker.io/library/nginx:latest
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    restart: always
